# configuration for master
-
  branches:
    only:
    - master

  environment:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  version: 1.0.0.{build}
  image: Visual Studio 2017
  configuration: Release
  install:
  - cmd: 
  build_script:
  - cmd: >-
      dotnet --info

      dotnet build Dynamic.Trader.sln --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%

  test: off
