version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a TraderDemo.zip %APPVEYOR_BUILD_FOLDER%\Trader.Client\bin\release\net46\*.*

    appveyor PushArtifact TraderDemo.zip
